# Simulation Exercises

In [1]:
import numpy as np
import pandas as pd

### 1. How likely is it that you roll doubles when rolling two dice?

In [10]:
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 1_000_000
n_trials = 2 

# Charles iteration comparing the roll [num1, num2] where all (num2) is equal to num1 (roll[0])
# rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))
# val = [roll for roll in rolls if np.all(roll == roll[0])]
# print(len(val)/len(rolls)*100)

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)
roll_a_double = (die1 == die2)
roll_a_double.mean()

0.165759

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [17]:
n_trials = n_rows = 1_000_000
coins = n_col = 8
heads = True # could also use 1,,, 1 would be the outcome I want
tails = False # could also use 0,,, 0 would be the outcome I don't want
outcomes = [heads, tails]

flips = np.random.choice(outcomes, size=(n_trials, coins))
flips

array([[False,  True,  True, ..., False, False, False],
       [False,  True,  True, ...,  True, False,  True],
       [False, False,  True, ..., False,  True,  True],
       ...,
       [False,  True,  True, ..., False, False, False],
       [False,  True,  True, ...,  True,  True,  True],
       [ True, False, False, ...,  True, False,  True]])

In [18]:
flips.sum(axis=1)

array([4, 4, 4, ..., 2, 7, 4])

In [19]:
numheads = flips.sum(axis=1)

In [22]:
prob = (numheads == 3).mean()
print(f'The probability that we will flip exactly 3 heads over {n_col} coins is {prob}')

The probability that we will flip exactly 3 heads over 8 coins is 0.218501


In [23]:
prob2 = (numheads >= 3).mean()
print(f'The probability that we will flip at least 3 heads over {n_col} coins is {prob2}')

The probability that we will flip at least 3 heads over 8 coins is 0.854511


### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [24]:
n_rows = 1_000_000
n_cols = 2
prob_ds = 0.25
data = np.random.random((n_rows, n_cols))
data

array([[0.79871151, 0.52852776],
       [0.75148828, 0.2896287 ],
       [0.1559973 , 0.50274701],
       ...,
       [0.83772984, 0.15359702],
       [0.23464592, 0.0691093 ],
       [0.50240993, 0.04553802]])

In [27]:
ds_billboard = data < prob_ds
ds_billboard

array([[False, False],
       [False, False],
       [ True, False],
       ...,
       [False,  True],
       [ True,  True],
       [False,  True]])

In [28]:
ds_billboard.sum(axis=1)

array([0, 0, 1, ..., 1, 2, 1])

In [25]:
((data < prob_ds).sum(axis=1) == 2).mean()

0.062057

In [29]:
((ds_billboard).sum(axis=1) == 2).mean()

0.062057

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [30]:
pop_avg = 3
pop_std = 1.5
days = n_cols = 5
n_trials = n_rows = 1_000_000
possible_poptarts_consumed = np.random.normal(pop_avg, pop_std, size=(n_rows, n_cols))
possible_poptarts_consumed

array([[4.81315718, 3.69226216, 4.90239369, 3.09373832, 2.47804249],
       [3.05382554, 3.83155731, 3.31858947, 1.95161228, 4.37455584],
       [2.75001475, 2.94079724, 2.49141149, 3.14820053, 1.56614176],
       ...,
       [4.09710888, 2.1280843 , 4.08339096, 4.54456409, 3.92255015],
       [4.84673835, 2.8655277 , 1.41552805, 2.65214787, 2.20479185],
       [5.18772776, 4.01468185, 4.47378215, 4.1787528 , 2.13109757]])

In [31]:
possible_poptarts_consumed.sum(axis=1)

array([18.97959384, 16.53014045, 12.89656578, ..., 18.77569836,
       13.98473381, 19.98604212])

In [33]:
calculated_prob = (possible_poptarts_consumed.sum(axis=1) <= 16).mean()
print(f'The probability that there will still be poptarts in the vending machine after {n_cols} days is {calculated_prob}')

The probability that there will still be poptarts in the vending machine after 5 days is 0.616635


### 5. Compare Heights
 - Men have an average height of 178 cm and standard deviation of 8cm.
 - Women have a mean of 170, sd = 6cm.
 - Since you have means and standard deviations, you can use np.random.normal to generate observations.
 - If a man and woman are chosen at random, P(woman taller than man)?

In [34]:
men_avg = 178
men_std = 8
wmn_avg = 170
wmn_std = 6
s_men = np.random.normal(men_avg, men_std, 1_000_000)
s_men[:5]

array([174.16922575, 175.58446731, 173.62173203, 178.83029317,
       180.05032911])

In [36]:
s_wmn = np.random.normal(wmn_avg, wmn_std, 1_000_000)
s_wmn

array([162.36536614, 167.25173201, 171.38489867, ..., 171.51605719,
       170.09045615, 169.16978908])

In [37]:
calculated_prob = (s_wmn > s_men).mean()
print(f'The probability that we will have a woman taller than a man presuming a normal distribution is {calculated_prob}')

The probability that we will have a woman taller than a man presuming a normal distribution is 0.212198


### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [42]:
nrows = 1_000_000
n_cols = 50
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [43]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) == 0).mean()

0.818759

In [44]:
n_cols = 100
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [45]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) == 0).mean()

0.668855

In [46]:
n_cols = 150
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [47]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) > 0).mean()

0.452286

In [48]:
n_cols = 450
conda_failure = 1
great_success = 0
prob_failure = (1/250)
prob_failure

0.004

In [49]:
installs = np.random.random((nrows, n_cols))
((installs < prob_failure).sum(axis=1) == 0).mean()

0.164919

In [56]:
# Review with Sam
p = [1/250, 249/250]

outcomes = [False, True]

n_students = 50

n_trials = 100_000

failures = np.random.choice(outcomes, size=[n_trials, n_students], p=p)

# john_outcomes = ([True] * 249).append(False)
# np.random.choice(john_outcomes, size=[n_trials, n_students])

df = pd.DataFrame(failures)
df['n_succeed'] = df.sum(axis=1)
df['all_succeed'] = df.n_succeed.mean()

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [50]:
n_rows = 1_000_000
n_cols = 3
food_truck = 1
no_truck = 0
truck_prob = 0.7
data = np.random.random((n_rows, n_cols))
((data < truck_prob).sum(axis=1) == 0).mean()

0.027034

In [51]:
n_rows = 1_000_000
n_cols = 2
food_truck = 1
no_truck = 0
truck_prob = 0.7

In [52]:
lunch_days = np.random.random((n_rows, n_cols))
calculated_prob = ((lunch_days < truck_prob).sum(axis=1) > 0).mean()
calculated_prob

0.910435

In [ ]:
# Review with Sam
n_days = 3
​
p = [3/10, 7/10]
​
outcomes = [False, True]
​
food_trucks = np.random.random([n_trials, n_days])
​
truck_df = pd.DataFrame(food_trucks)
​
truck_df = truck_df.apply(lambda x: x<.7)
​
truck_df['truck_sum'] = truck_df.sum(axis=1)
​
truck_df['no_trucks'] = truck_df.truck_sum == 0

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [57]:
outcomes = range(0, 365)
n_trials = 23
n_simulations = 1_000_000
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [58]:
list_of_twin_bdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulations-1) if len(np.unique(classrooms[n])) < 23]

In [59]:
prop_twinsies = len(list_of_twin_bdays) / n_simulations
prop_twinsies

0.507088

In [60]:
outcomes = range(0, 365)
n_trials = 20
n_simulations = 1_000_000
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [61]:
list_of_twin_bdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulations-1) if len(np.unique(classrooms[n])) < 20]

In [62]:
prop_twinsies = len(list_of_twin_bdays) / n_simulations
prop_twinsies

0.411171

In [63]:
outcomes = range(0, 365)
n_trials = 40
n_simulations = 1_000_000
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [64]:
list_of_twin_bdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulations-1) if len(np.unique(classrooms[n])) < 40]

In [65]:
prop_twinsies = len(list_of_twin_bdays) / n_simulations
prop_twinsies

0.891143